plugins {
  id 'java-library'
}

group = 'com.pnambic.modxstream'
version = '0.0.0-a'
sourceCompatibility = '21'

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  implementation "com.google.guava:guava:${guavaVersion}"
  implementation "com.thoughtworks.xstream:xstream:${xstreamVersion}"
  implementation "org.slf4j:slf4j-api:${slf4jVersion}"
}

java {
  withJavadocJar()
  withSourcesJar()
}

tasks.named('test') {
  // Use JUnit Platform for unit tests.
   useJUnitPlatform()
}

jar {
  manifest {
    attributes 'Automatic-Module-Name': 'pnambic.modxstream'
  }
}
